### PR TITLE
Fix typos in grade-school test & pig-latin example

### PR DESCRIPTION
**Pull request by thomchop**

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Thanks a lot @thomchop! The build failure is unrelated to your change. I'll wait for one of the Clojure maintainers to look at this. If they don't have the time to look at this, I'll merge it tomorrow or so.

**Comment by haus** [comment]
#299 seems to resolve the current travis issues.

**Review by porkostomus — APPROVED** [review]

**Comment by thomchop** [comment]
Yeah I thought I recognized the cause of that travis failure.. 🙂 
Looked like the same issue that I'd fixed on the Swift repo (exercism/swift#400). I was gonna go ahead and fix it here but then I thought maybe we should go ahead and set up GitHub actions, instead of worrying about travis.

**Comment by ErikSchierboom** [comment]
> I was gonna go ahead and fix it here but then I thought maybe we should go ahead and set up GitHub actions, instead of worrying about travis.

This is definitely the way to go! 👍

**Comment by ErikSchierboom** [comment]
Thanks for the fix @thomchop!

**Pull request merged**
