### PR TITLE
Add rotational-cipher puzzle with tests and solution.

### PR DESCRIPTION
**Pull request by mwfogleman**
Added the rotational-cipher puzzle with tests and solution.

https://github.com/exercism/x-common/blob/master/exercises/rotational-cipher/description.md

### CODE REVIEW

**Comment by yurrriq** [comment]
Thanks. This looks pretty good, but could you please make the internal definitions private?

It would also be good to put blank lines between the top-level definitions, but I don't feel strongly about that, so it's up to you.

I also wonder if we could make use of `mapcat`.

**Comment by mwfogleman** [comment]
I added blank lines, made the internal function private (but not the variables), and added the metadata to the config.json file.

The solution does not include mapcat at this time.

**Comment by yurrriq** [comment]
Looks like `config.json` is missing a `,` and causing the Travis build to fail. Could you please add `^:private` to the `def`s too? I'm fine with the current `mapcat`-less implementation.

**Comment by mwfogleman** [comment]
Ah, that's why! Thanks. Done and done. :)

**Comment by yurrriq** [comment]
LGTM, thanks!

**Pull request merged**
