### PR TITLE
Implementing complex-numbers

### PR DESCRIPTION
**Pull request by Average-user**
.

### CODE REVIEW

**Comment by haus** [comment]
This looks good to me. It looks like it needs a rebase to account for some changes to config.json.

**Comment by Average-user** [comment]
@haus Don't exactly know what you mean with that.

**Comment by haus** [comment]
@Average-user it just means that there were changes made to config.json that git can't resolve automatically. There are a couple of ways to resolve the conflict:

1. Try the 'Resolve conflicts' button in the PR screen (https://help.github.com/articles/resolving-a-merge-conflict-on-github/ seems like a good resource)
2. Try resolving the conflict on the command line (https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ seems like a good resource)

**Comment by haus** [comment]
Hmm. Looks like there are still conflicts. I'll try to pull this down and fix the conflicts.

**Comment by haus** [comment]
Oops. I didn't mean to do that. https://github.com/exercism/clojure/pull/195 has the conflicts resolved.

**Comment by Average-user** [comment]
@haus I was trying something too. But it haven't been working.

**Comment by haus** [comment]
Cool

**Pull request closed without merging**
