### PR TITLE
adding series

### PR DESCRIPTION
**Pull request by Average-user**
another Unimplemented exercise.

### CODE REVIEW

**Comment by yurrriq** [comment]
Thanks! After a cursory glance on my phone, this looks good. @haus?

**Comment by haus** [comment]
I'm in. Thanks @Average-user !

**Comment by Average-user** [comment]
@yurrriq @haus  Thanks to you. (There's another on the way, probably)

**Comment by haus** [comment]
Awesome! looking forward to it.

**Pull request merged**
