### PR TITLE
Complex numbers: Sync tests with problem-specifications

### PR DESCRIPTION
**Pull request by tasxatzial**
Partially addresses #520 

Tests are now in sync, missing tests have been implemented, order of the actual and expected results has been fixed.

I'll try to address the issue with the floats in a subsequent PR since this one is changes a lot of things.

### CODE REVIEW

**Comment by bobbicodes** [comment]
For some reason it's not giving me the option to reopen this... weird

**Comment by bobbicodes** [comment]
Oh, now it is :)

**Comment by bobbicodes** [comment]
I still find it odd that the expected/actual results depend on the order in the `=` expression. I'm trying to see if that is documented anywhere but it doesn't seem to be.

**Comment by tasxatzial** [comment]
Ok, so i had a suspicion that the order of actual expected is nothing more than a convention. The Clojure api [here](https://clojure.github.io/clojure/clojure.test-api.html) shows an example with expected being the initial form and actual being the computed result. Re-writing `(= 5 (+ 2 2))` as `(= (+ 2 2) 5)` simply switches the initial form, but this doesn't really make any difference because the actual form remains the same. I've tested this with the online editor and with lein and both don't care about the order.

The confusion about the convention arises when we realize that not every test tool behaves like this. Cursive, for example, reports something completely different.

`(is (= 5 (+ 2 2))) -> Expected 4, Actual 5`
`(is (= (+ 2 2) 5)) -> Expected 5, Actual 4`

So not only it does not retain the initial form, but now the order makes a difference. It treats the first argument as the actual and the second as the expected. But apparently for most test tools the order comes from the Clojure api and is the exact opposite: First is expected, second is actual.

How do i know this? I just asked the Cursive author [here](https://groups.google.com/g/cursive/c/NQ1tX1edeUg). So I'll leave the order as is and hopefully some day he fixes Cursive.

**Comment by tasxatzial** [comment]
This one is finished. Tested with random community solutions and i've found one that fails due to floating point inaccuracies. The good news is that the next PR, which is ready, will resolve those issues.

**Review by bobbicodes — APPROVED** [review]
Cool, thanks!

**Pull request merged**
