### PR TITLE
Flip Concept exercises from "wip" to "beta"

### PR DESCRIPTION
**Pull request by porkostomus**
I think this might be the last step to get them live.

### CODE REVIEW

**Review by SleeplessByte — APPROVED** [review]

**Comment by SleeplessByte** [comment]
Here we go 🚀 . EXCITING @porkostomus !!!!

**Comment by porkostomus** [comment]
I should have realized that they won't work until the new test runner is merged: https://github.com/exercism/clojure-test-runner/pull/18

**Comment by SleeplessByte** [comment]
@porkostomus want me to just approve that and see what happens :P ?

**Comment by porkostomus** [comment]
Sure, I'll be standing by to deal with any unexpected consequences.

**Pull request merged**
