### PR TITLE
Clojure/change: Add new test for invalid amount/coins combination

### PR DESCRIPTION
**Pull request by 0xRand0m**
Hi, I think this would be a worthwhile addition to the tests because it requires more elaborate checks inside the solution algorithm.

### CODE REVIEW

**Comment by BTowersCoding** [comment]
Awesome, love it! Except that it seems we might need to update the example solution because CI is failing. Unless something else is broken... I'll try to look into this today.

**Comment by 0xRand0m** [comment]
This is my solution which passes the test. Use any part you like ;)
```clojure
(ns change)

(def algo
  (memoize (fn [amount coins]
             (let [smaller (filter #(<= % amount) coins)]
               ; use a list so that amount always stays the first element
               (if (empty? smaller) `(~amount)
                 (apply min-key
                        count
                        ; check if valid solution, i.e. the final amount was zero
                        (filter (comp zero? first)
                                (map
                                  (fn [coin]
                                    (concat
                                      (algo (rem amount coin) smaller)
                                      (repeat (quot amount coin) coin)))
                                  smaller))))))))


(defn issue [amount coins] 
  (try
    (let [[x & xs] (algo amount coins)]
      (if (zero? x) xs
        (throw (IllegalArgumentException. "cannot change"))))
    ; thrown by apply min-key if we don't have the right coins to issue change
    (catch clojure.lang.ArityException e (throw (IllegalArgumentException. "cannot change")))))
```

**Comment by BTowersCoding** [comment]
Yes, that works great!

If you'd like, the easiest way would probably be for you to make another commit to https://github.com/exercism/clojure/blob/main/exercises/practice/change/.meta/src/example.clj replacing the existing code with your solution above.

**Comment by BTowersCoding** [comment]
I thought I smelled something funny, there seems to be a bug in the test runner as well

**Comment by BTowersCoding** [comment]
I might have found the issue: https://github.com/exercism/clojure/pull/473

**Review by BTowersCoding — APPROVED** [review]

**Pull request merged**
